### ISSUE TITLE
Narrative (script, text, etc).

### ISSUE THREAD

**Issue by stoversa** [dawnwages/TheUltimateGame#10]
We need a script that covers the whole game: A user's pet has been kidnapped by an evil wizard. The user must face challenges in order for the final confrontation to free their pet from the evil wizard's clutches.

**Comment by jmarrano09** [comment]
Let's have an outline for the script:
Characters: How many? Who are they? I'm including the side characters as well.
Conflict: What's the purpose?

The script itself can be pretty basic.  A user chooses a pet.  That pet is kidnapped by an evil wizard. The user must face challenges in order to get their pet back and win the game.  Now we need some dialogue.  We already have the challenges that the user must go through the retrieve said pet.
